-- Enhanced intelephense.lua (focused on navigation/completion)
return {
  settings = {
    intelephense = {
      environment = {
        phpVersion = "8.2.0",
        includePaths = { "vendor" },
      },
      stubs = {
        "Core",
        "SPL",
        "Reflection",
        "standard",
        "superglobals",
        "apache",
        "bcmath",
        "bz2",
        "calendar",
        "ctype",
        "curl",
        "date",
        "dba",
        "dom",
        "enchant",
        "exif",
        "FFI",
        "fileinfo",
        "filter",
        "ftp",
        "gd",
        "gettext",
        "gmp",
        "hash",
        "iconv",
        "imap",
        "intl",
        "json",
        "ldap",
        "libxml",
        "mbstring",
        "meta",
        "mysqli",
        "oci8",
        "odbc",
        "openssl",
        "pcntl",
        "pcre",
        "PDO",
        "pdo_mysql",
        "pdo_pgsql",
        "pdo_sqlite",
        "pgsql",
        "Phar",
        "posix",
        "pspell",
        "readline",
        "session",
        "shmop",
        "SimpleXML",
        "snmp",
        "soap",
        "sockets",
        "sodium",
        "sqlite3",
        "sysvmsg",
        "sysvsem",
        "sysvshm",
        "tidy",
        "tokenizer",
        "xml",
        "xmlreader",
        "xmlrpc",
        "xmlwriter",
        "xsl",
        "Zend OPcache",
        "zip",
        "zlib",
        "laravel",
        "lumen",
      },
      files = {
        maxSize = 5000000,
        associations = { "*.php", "*.phtml" },
        exclude = {
          "**/node_modules/**",
          "**/bower_components/**",
          "**/.git/**",
          "**/storage/**",
          "**/bootstrap/cache/**",
          "**/public/build/**",
          "**/public/hot",
          "**/public/storage/**",
          "**/cache/**",
          "**/build/**",
          -- Exclude test files to reduce memory
          "**/vendor/**/Tests/**",
          "**/vendor/**/tests/**",
          "**/vendor/**/test/**",
          -- Exclude heavy dev dependencies
          "**/vendor/bin/**",
          "**/vendor/composer/**",
          "**/vendor/phpunit/**",
          "**/vendor/phpstan/**",
          "**/vendor/psalm/**",
          "**/vendor/mockery/**",
          "**/vendor/fakerphp/**",
          "**/vendor/psy/**",
          "**/vendor/nunomaduro/collision/**",
          "**/vendor/filp/whoops/**",
        },
      },
      completion = {
        insertUseDeclaration = true,
        fullyQualifyGlobalConstantsAndFunctions = false,
        triggerParameterHints = true,
        maxItems = 100,
      },
      cache = {
        workspace = {
          enable = true,
        },
      },
      diagnostics = {
        enable = true,
        run = "onType",
        typeErrors = false,
        undefinedTypes = true,
        undefinedFunctions = true,
        undefinedConstants = true,
        undefinedClassConstants = true,
        undefinedMethods = true,
        undefinedProperties = true,
        unusedSymbols = true,
        duplicateSymbols = false,
        argumentCount = true,
        typeCoercion = false,
        missingReturnType = false,
        unnecessaryFQCN = false,
      },
      format = {
        enable = false,
      },
      telemetry = {
        enabled = false,
      },
    },
  },
  on_attach = function(client, bufnr)
    -- Intelephense handles: navigation, completion, hover, diagnostics
    client.server_capabilities.documentFormattingProvider = false
    client.server_capabilities.documentRangeFormattingProvider = false
    -- Disable rename for Intelephense (let phpactor handle it)
    client.server_capabilities.renameProvider = false
  end,
}
