#!/usr/bin/env bash

class=$(playerctl metadata --player=spotify --format '{{lc(status)}}')

if [[ $class == "paused" ]]; then
  icon=""
else
  icon=""
fi

if [[ $class == "playing" ]]; then
  info=$(playerctl metadata --player=spotify --format '{{artist}} - {{title}}')

  if [[ ${#info} -gt 40 ]]; then
    info=$(echo $info | cut -c1-36)"..."
  fi

  text=$icon" "$info
elif [[ $class == "paused" ]]; then
  info=$(playerctl metadata --player=spotify --format '{{artist}} - {{title}}')

  if [[ ${#info} -gt 40 ]]; then
    info=$(echo $info | cut -c1-36)"..."
  fi

  text=$icon" "$info
elif [[ $class == "stopped" ]]; then
  text=""
fi

echo -e "{\"text\":\""$text"\", \"class\":\""$class"\"}"
