windowrule {
  name = ghostty
  match:class = ghostty

  opacity = 1.0 0.5
}

windowrule {
  name = file-progress
  match:class = file_progress

  float = on
}

windowrule {
  name = confirm
  match:class = confirm

  float = on
}

windowrule {
  name = dialog
  match:class = dialog

  float = on
}

windowrule {
  name = download
  match:class = download

  float = on
}

windowrule {
  name = notification
  match:class = notification

  float = on
}

windowrule {
  name = error
  match:class = error

  float = on
}

windowrule {
  name = splash
  match:class = splash

  float = on
}

windowrule {
  name = confirmreset
  match:class = confirmreset

  float = on
}

windowrule {
  name = open-file
  match:title = Open File

  float = on
}

windowrule {
  name = branchdialog
  match:title = branchdialog

  float = on
}

windowrule {
  name = lxappearance
  match:class = Lxappearance

  float = on
}

windowrule {
  name = rofi
  match:class = Rofi

  float = on
  no_anim = on
  dim_around = on
}

windowrule {
  name = viewnior
  match:class = viewnior

  float = on
  size = 1720 1080
  center = on
}

windowrule {
  name = feh
  match:class = feh

  float = on
}

windowrule {
  name = pavucontrol-qt
  match:class = pavucontrol-qt

  float = on
}

windowrule {
  name = pavucontrol
  match:class = pavucontrol

  float = on
}

windowrule {
  name = file-roller
  match:class = file-roller

  float = on
}


windowrule {
  name = mpv
  match:class = mpv

  idle_inhibit = focus
}

windowrule {
  name = google-chrome
  match:class = google-chrome

  idle_inhibit = fullscreen
}


windowrule {
  name = media-viewer
  match:title = ^(Media viewer)$

  float = on
}

windowrule {
  name = volume-control
  match:title = ^(Volume Control)$

  float = on
  size = 800 600
  move = 75 44%
}

windowrule {
  name = picture-in-picture
  match:title = ^(Picture-in-Picture)$

  float = on
}

windowrule {
  name = floating-windows
  match:float = true

  border_size = 0
}

windowrule {
  name = thunderbird
  match:class = thunderbird

  workspace = 5
}
