windowrule {
  name = ghostty
  match:class = ghostty

  opacity = 1.0 0.5
}

windowrule {
  name = file-progress
  match:class = file_progress

  float = on
}

windowrule {
  name = confirm
  match:class = confirm

  float = on
}

windowrule {
  name = dialog
  match:class = dialog

  float = on
}

windowrule {
  name = download
  match:class = download

  float = on
}

windowrule {
  name = notification
  match:class = notification

  float = on
}

windowrule {
  name = error
  match:class = error

  float = on
}

windowrule {
  name = splash
  match:class = splash

  float = on
}

windowrule {
  name = confirmreset
  match:class = confirmreset

  float = on
}

windowrule {
  name = open-file
  match:title = Open File

  float = on
}

windowrule {
  name = branchdialog
  match:title = branchdialog

  float = on
}

windowrule {
  name = lxappearance
  match:class = Lxappearance

  float = on
}

windowrule {
  name = rofi
  match:class = Rofi

  float = on
  no_anim = on
  dim_around = on
}

windowrule {
  name = viewnior
  match:class = viewnior

  float = on
  size = 1720 1080
  center = on
}

windowrule {
  name = feh
  match:class = feh

  float = on
}

windowrule {
  name = pavucontrol-qt
  match:class = pavucontrol-qt

  float = on
}

windowrule {
  name = pavucontrol
  match:class = pavucontrol

  float = on
}

windowrule {
  name = file-roller
  match:class = file-roller

  float = on
}

windowrule {
  name = wlogout
  match:class = wlogout

  float = on
  fullscreen = on
}

windowrule {
  name = mpv
  match:class = mpv

  idle_inhibit = focus
}

windowrule {
  name = firefox
  match:class = firefox

  idle_inhibit = fullscreen
}

windowrule {
  name = firefox-work
  match:class = firefox-work

  idle_inhibit = fullscreen
  workspace = 1
}

windowrule {
  name = firefox-personal
  match:class = firefox-personal

  idle_inhibit = fullscreen
  workspace = 5
}

windowrule {
  name = media-viewer
  match:title = ^(Media viewer)$

  float = on
}

windowrule {
  name = volume-control
  match:title = ^(Volume Control)$

  float = on
  size = 800 600
  move = 75 44%
}

windowrule {
  name = picture-in-picture
  match:title = ^(Picture-in-Picture)$

  float = on
}

windowrule {
  name = floating-windows
  match:float = true

  border_size = 0
}

windowrule {
  name = thunderbird
  match:class = thunderbird

  workspace = 6
}

windowrule {
  name = vesktop
  match:class = vesktop

  workspace = 11
}

windowrule {
  name = teams-for-linux
  match:class = teams-for-linux

  workspace = 12
}

windowrule {
  name = steam
  match:class = steam

  workspace = 9
  float = on
}

windowrule {
  name = prominence
  match:class = Prominence™ II: Hasturian Era

  fullscreen_state = 2 2
  content = game
  immediate = on
  suppress_event = fullscreen
  no_follow_mouse = on
}
